### ISSUE TITLE
Increment and decrement functions should allow an integer

### ISSUE THREAD

**Issue by David-Gil** [PanagiotisGeorgiadis/Elm-DateTime#1]
Hi,

Functions for incrementing only sum up one unit. Functions for decrementing only substract one unit.

There should be functions for adding and substracting a given number of units.

Maybe current increment and decrement functions should build on top of these new functions.

I'm willing to help coding it.

**Comment by PanagiotisGeorgiadis** [comment]
Hello there @David-Gil, my initial thought on this use case was that **_we should provide the basic tools for the consumer and the consumer should be the on who builds on top of those._** I am building a DatePicker component on the same time and I've found that it is easier for me to build on top of the Elm-DateTime than try to make the Elm-DateTime as generic as possible.

You can take a look at [this file](https://github.com/PanagiotisGeorgiadis/ElmDatePicker/blob/master/src/Utils/DateTime.elm#L16) on how we extended the increment and decrement functions.

Also, please bare in mind that our `Clock` module returns a tuple `( Time, Bool )` where the `Bool` indicates if there has been a "full cycle" in hours, minutes, seconds, milliseconds. If we change the logic on these functions to support multiple increment and decrements we may lose information. For example think of incrementing an hour 48 times. The minimum number of cycles will be 2 but we will only be able to track 1 and hence incrementing the `Day` part only once. 

On the other hand the [DateTime.incrementHours](https://github.com/PanagiotisGeorgiadis/Elm-DateTime/blob/master/src/DateTime/Internal.elm#L500) could accept and `Int` and perform the process above which would result in the correct result.

What do you think of the above ?

**Comment by David-Gil** [comment]
Hi! :smile:  

After publishing this issue here, I continued investigating and found the way to add hours to a DateTime using the elm/time package:

First I convert it to Unix timestamp in milliseconds. Then it is as simple as milliseconds + (hours * 3600000). From there it is very easy to convert to Posix and whichever format needed.

In summary, I've shifted to using Unix timestamp in milliseconds as the base unit to make calculations since I only add hours to a given DateTime. 

For me, it's a little awkward to try to use a function that only increments or decrements a unit, but for your DatePicker (your use case) that functionality is perfect.

Cheers!

**Comment by PanagiotisGeorgiadis** [comment]
Hello again @David-Gil! 😃 

What you came up with seems to be working just fine! I would suggest taking a look at implementing your own helper functions for performing multiple "steps" when using the increment / decrement functions instead of going back and forth from Posix.

One of the many approaches could be the following example:

```
incrementHours : Int -> DateTime -> DateTime
incrementHours steps dateTime =
    if steps > 0 then
        incrementHours (steps - 1) (DateTime.incrementHours dateTime)

    else
        dateTime


decrementHours : Int -> DateTime -> DateTime
decrementHours steps dateTime =
    if steps > 0 then
        decrementHours (steps - 1) (DateTime.decrementHours dateTime)

    else
        dateTime
``` 

If you would like to look at some more involved examples please take a look at this [example application](https://ellie-app.com/4Vh4vRt65wba1).

Happy coding!

**Comment by David-Gil** [comment]
I'm so sorry I didn't respond until now.

I find your recursive code very interesting, thank your for sharing it. The thing is I am incrementing 48 hours and could reach to 72 hours in the future. That's a lot of calls to a function (although I don't know how expensive it can get). That's why I stick with my code for my specific use case.

Anyway, I'll take your library into account if I need it in the future! :smiley: 

Cheers,

David Gil

**Comment by bburdette** [comment]
How about 

```
addDays : Int -> Calendar.Date -> Calendar.Date
addDays days date =
    let
        millis =
            Time.posixToMillis (Time.millisToPosix (Calendar.toMillis date)) + (Calendar.millisInADay * days)

        newDate =
            Calendar.fromPosix (Time.millisToPosix millis)
    in
    newDate
```

Then incrementDay is just `addDays 1`.

If you want to add 50 days, and you call `incrementDay` 50 times, then you've done all those posix to millis conversions 50 times.  `addDays 50` would only do the conversion once.

**Comment by bburdette** [comment]
Actually it might be a good idea to add 12 hours of millis after converting the date, to make leap second bugs less likely
